// Code generated by protoc-gen-go and protoc-gen-go-grpc. DO NOT EDIT.
// This is a simplified version for demonstration purposes.
// In a real project, you would generate this using protoc.

package transport

import (
	"context"
	"io"

	"google.golang.org/grpc"
)

// AgentServiceClient is the client API for AgentService service
type AgentServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (AgentService_StreamClient, error)
	SendTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	TransferFile(ctx context.Context, opts ...grpc.CallOption) (AgentService_TransferFileClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewAgentServiceClient creates a new AgentService client
func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (AgentService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], "/transport.AgentService/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceStreamClient{stream}
	return x, nil
}

type AgentService_StreamClient interface {
	Send(*StreamMessage) error
	Recv() (*StreamMessage, error)
	grpc.ClientStream
}

type agentServiceStreamClient struct {
	grpc.ClientStream
}

func (x *agentServiceStreamClient) Send(m *StreamMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceStreamClient) Recv() (*StreamMessage, error) {
	m := new(StreamMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) SendTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/transport.AgentService/SendTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/transport.AgentService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/transport.AgentService/ExecuteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) TransferFile(ctx context.Context, opts ...grpc.CallOption) (AgentService_TransferFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], "/transport.AgentService/TransferFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceTransferFileClient{stream}
	return x, nil
}

type AgentService_TransferFileClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*FileTransferResponse, error)
	grpc.ClientStream
}

type agentServiceTransferFileClient struct {
	grpc.ClientStream
}

func (x *agentServiceTransferFileClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceTransferFileClient) CloseAndRecv() (*FileTransferResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileTransferResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Message types (simplified structs for demonstration)
type StreamMessage struct {
	Id        string            `json:"id"`
	Type      string            `json:"type"`
	Timestamp int64             `json:"timestamp"`
	AgentId   string            `json:"agent_id"`
	ReplyTo   string            `json:"reply_to"`
	Data      []byte            `json:"data"`
	Metadata  map[string]string `json:"metadata"`
}

type TaskRequest struct {
	TaskId     string            `json:"task_id"`
	TaskType   string            `json:"task_type"`
	Command    string            `json:"command"`
	Args       []string          `json:"args"`
	Env        map[string]string `json:"env"`
	WorkingDir string            `json:"working_dir"`
	Timeout    int32             `json:"timeout"`
	Metadata   map[string]string `json:"metadata"`
}

type TaskResponse struct {
	TaskId     string `json:"task_id"`
	Status     string `json:"status"`
	ExitCode   int32  `json:"exit_code"`
	Stdout     string `json:"stdout"`
	Stderr     string `json:"stderr"`
	StartedAt  int64  `json:"started_at"`
	FinishedAt int64  `json:"finished_at"`
	Error      string `json:"error"`
}

type StatusRequest struct {
	IncludeMetrics bool `json:"include_metrics"`
	IncludeTasks   bool `json:"include_tasks"`
}

type StatusResponse struct {
	AgentId      string                 `json:"agent_id"`
	Status       string                 `json:"status"`
	Version      string                 `json:"version"`
	Uptime       int64                  `json:"uptime"`
	Metrics      *SystemMetrics         `json:"metrics"`
	RunningTasks []*TaskInfo            `json:"running_tasks"`
	Metadata     map[string]string      `json:"metadata"`
}

type SystemMetrics struct {
	CpuUsage     float64 `json:"cpu_usage"`
	MemoryUsage  float64 `json:"memory_usage"`
	DiskUsage    float64 `json:"disk_usage"`
	NetworkRx    int64   `json:"network_rx"`
	NetworkTx    int64   `json:"network_tx"`
	ProcessCount int32   `json:"process_count"`
}

type TaskInfo struct {
	TaskId    string `json:"task_id"`
	TaskType  string `json:"task_type"`
	Status    string `json:"status"`
	StartedAt int64  `json:"started_at"`
	Progress  int32  `json:"progress"`
}

type CommandRequest struct {
	Command       string            `json:"command"`
	Args          []string          `json:"args"`
	Env           map[string]string `json:"env"`
	WorkingDir    string            `json:"working_dir"`
	Timeout       int32             `json:"timeout"`
	CaptureOutput bool              `json:"capture_output"`
}

type CommandResponse struct {
	ExitCode      int32  `json:"exit_code"`
	Stdout        string `json:"stdout"`
	Stderr        string `json:"stderr"`
	ExecutionTime int64  `json:"execution_time"`
	Error         string `json:"error"`
}

type FileChunk struct {
	FileId    string            `json:"file_id"`
	Filename  string            `json:"filename"`
	Offset    int64             `json:"offset"`
	Data      []byte            `json:"data"`
	TotalSize int64             `json:"total_size"`
	IsLast    bool              `json:"is_last"`
	Metadata  map[string]string `json:"metadata"`
}

type FileTransferResponse struct {
	FileId           string `json:"file_id"`
	Status           string `json:"status"`
	BytesTransferred int64  `json:"bytes_transferred"`
	Checksum         string `json:"checksum"`
	Error            string `json:"error"`
}

// Service descriptor (simplified)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transport.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTask",
			Handler:    nil, // Would be implemented by server
		},
		{
			MethodName: "GetStatus",
			Handler:    nil, // Would be implemented by server
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    nil, // Would be implemented by server
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       nil, // Would be implemented by server
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferFile",
			Handler:       nil, // Would be implemented by server
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}

// AgentServiceServer is the server API for AgentService service
type AgentServiceServer interface {
	Stream(AgentService_StreamServer) error
	SendTask(context.Context, *TaskRequest) (*TaskResponse, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	TransferFile(AgentService_TransferFileServer) (*FileTransferResponse, error)
}

type AgentService_StreamServer interface {
	Send(*StreamMessage) error
	Recv() (*StreamMessage, error)
	grpc.ServerStream
}

type AgentService_TransferFileServer interface {
	SendAndClose(*FileTransferResponse) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}